#!/bin/sh
free_dpkg() {
    echo freeing dpkg
    /bin/rm -f /var/lib/dpkg/lock
    /bin/rm -f /var/lib/aegis/restok/restok.conf.lock
    /bin/rm -f /var/cache/apt/archives/lock
}
dbus-send --print-reply --dest=com.meego.core.MNotificationManager /notificationmanager com.meego.core.MNotificationManager.addNotification uint32:1000 uint32:0 string:'x-nokia.internet' string:"" string:"TLS fix installing. You may see warnings, dont worry - its okay." string:'' string:'' uint32:0
echo "backuping installer package status"
if [ -d /var/lib/dpkg/updates ]
then
    /bin/mv /var/lib/dpkg/updates /var/lib/dpkg/updates.old || true
    /bin/mkdir -p /var/lib/dpkg/updates || true
else
    /bin/mkdir -p /var/lib/dpkg/updates || true
fi

free_dpkg
aegis-dpkg -i /usr/share/tls-fix/first/wunderw-perl-opt_5.38.0-1_armel.deb

free_dpkg
aegis-dpkg -i /usr/share/tls-fix/first/openssl-local_1.0.2u_armel.deb


for f in /usr/share/tls-fix/*.deb; do
    echo installing $f
    free_dpkg
    aegis-dpkg -i $f
done

echo "returning installer package status"
if [ -d /var/lib/dpkg/updates.old ]; then
    /bin/rm -rf /var/lib/dpkg/updates || true
    /bin/mv -f /var/lib/dpkg/updates.old /var/lib/dpkg/updates || true
fi
if [ ! -d /var/lib/dpkg/updates ]; then
    /bin/mkdir -p /var/lib/dpkg/updates || true
fi